var attr = DS.attr;

var Superhero = DS.Model.extend({
  fullName: attr('string'),
  email: attr('string'),
  twitterUrl: attr('string'),
  facebookUrl: attr('string'),
  gplusUrl: attr('string'),
  pnProfileUrl: attr('string'),
  picUrl: attr('string'),
  discPicUrl: attr('string'),
  whatILove: attr('string'),
  whatIHate: attr('string'),
  whatINeed: attr('string'),
  majorDiscStyle: attr('string'),
  superpowers: attr('string'),
  priorities: attr('string'),
  assertiveness: DS.attr('number'),
  aggressiveness: DS.attr('number'),
  egoDrive: DS.attr('number'),
  empathy: DS.attr('number'),
  egoStrengthResilience: DS.attr('number'),
  riskTaking: DS.attr('number'),
  urgency: DS.attr('number'),
  cautiousness: DS.attr('number'),
  sociability: DS.attr('number'),
  gregariousness: DS.attr('number'),
  accommodation: DS.attr('number'),
  skepticism: DS.attr('number'),
  abstractReasoning: DS.attr('number'),
  ideaOrientation: DS.attr('number'),
  thoroughness: DS.attr('number'),
  flexibility: DS.attr('number'),
  selfStructure: DS.attr('number'),
  externalStructure: DS.attr('number'),

  discStyles: {
    'iD': {
            name: 'influence/Dominance',
            opposites: ['CS', 'C', 'SC'],
            similar: ['Di', 'iD', 'i']
          },
    'i' : {
            name: 'influence',
            opposites: ['C', 'CD', 'CS'],
            similar: ['iD', 'i', 'iS']
          },
    'iS': {
            name: 'influence/Support',
            opposites: ['CD', 'C', 'D'],
            similar: ['iS', 'i', 'Si']
          },
    'Si': {
            name: 'Support/influence',
            opposites: ['DC', 'CD', 'D'],
            similar: ['Si', 'S', 'iS']
          },
    'S' : {
            name: 'Support',
            opposites: ['D', 'DC', 'Di'],
            similar: ['S', 'Si', 'SC']
          },
    'SC': {
            name: 'Support/Conscientiousness',
            opposites: ['Di', 'D', 'iD'],
            similar: ['SC', 'S', 'CS']
          },
    'CS': {
            name: 'Conscientiousness/Support',
            opposites: ['iD', 'i', 'Di'],
            similar: ['CS', 'SC', 'C']
          },
    'C' : {
            name: 'Conscientiousness',
            opposites: ['iD', 'i', 'iS'],
            similar: ['C', 'CD', 'CS']
          },
    'CD': {
            name: 'Conscientiousness/Dominance',
            opposites: ['iS', 'i', 'Si'],
            similar: ['CD', 'C', 'DC']
          },
    'DC': {
            name: 'Dominance/Conscientiousness',
            opposites: ['Si', 'S', 'iS'],
            similar: ['DC', 'CD', 'D']
          },
    'D' : {
            name: 'Dominance',
            opposites: ['SC', 'S', 'Si'],
            similar: ['D', 'DC', 'Di']
          },
    'Di': {
            name: 'Dominance/influence',
            opposites: ['SC', 'S', 'CS'],
            similar: ['D', 'Di', 'iD']
          }
  },

  discStyleDescription: function() {
    var style = this.get('majorDiscStyle');
    var styles = this.get('discStyles');
    return(styles[style].name);
  }.property('majorDiscStyle', 'discStyles'),

  discStyleOpposites: function() {
    var style = this.get('majorDiscStyle');
    var styles = this.get('discStyles');
    var opposites = styles[style].opposites;

    var controller = this;

    var heroes = controller.store.all('superhero');
    heroes = heroes.rejectBy('id',controller.get('id'));

    var results = [];
    var heroesWhoAreOpposites = [];

    opposites.forEach(function(opposite) {
      heroesWhoAreOpposites = heroes
                                .filterBy('majorDiscStyle', opposite);

      if (!heroesWhoAreOpposites) {
        return([]);
      }

      heroesWhoAreOpposites.forEach(function (opp){
        results = $.merge(results, [opp]).slice(0, 5);
      });
    });

    return(results);
  }.property('majorDiscStyle', 'discStyles'),

  discStyleSimilar: function() {
    var style = this.get('majorDiscStyle');
    var styles = this.get('discStyles');
    var similar = styles[style].similar;

    var controller = this;

    var heroes = controller.store.all('superhero');
    heroes = heroes.rejectBy('id',controller.get('id'));

    var results = [];
    var heroesWhoAreSimilar = [];

    similar.forEach(function(obj) {
      heroesWhoAreSimilar = heroes
                              .filterBy('majorDiscStyle', obj);

      if (!heroesWhoAreSimilar) {
        return([]);
      }

      heroesWhoAreSimilar.forEach(function (obj){
        results = $.merge(results, [obj]).slice(0, 5);
      });
    });

    return(results);
  }.property('majorDiscStyle', 'discStyles'),
    /* similarityMatrix is a computed property
   * it triggers once per route transition - when the id of the controller's model changes
   * it really depends on all of the Caliper attributes, but expressing that dependency causes
   * it to fire once per attribute, and there seems to be no way to ask which attribute
   * caused it to trigger.
   * Returns an object indexed by the attributes, containing "similar" and "dissimilar"
   * arrays of superheroes
   */
  similarityMatrix: function() {
    // loop through the attribute names, building a list of the most different superheroes for each name
    var attributes = ['assertiveness', 'aggressiveness', 'egoDrive', 'empathy', 'egoStrengthResilience', 'riskTaking', 'urgency', 'cautiousness', 'sociability', 'gregariousness', 'accommodation', 'skepticism', 'abstractReasoning', 'ideaOrientation', 'thoroughness', 'flexibility', 'selfStructure', 'externalStructure'];

    // this won't mean the same thing inside the loop so hang on to it
    var controller = this;

    // accumulate similarities here, indexed by attribute
    var attributeSimilarities = {};

    /* FIXME - implement KSD's algorithm for dissimilar heroes
     *
     * "least like me" = >40 points
     * thus "least like me" with a 20 would have to be a 60 or more
     * and "least like me" could be <10 or >90 with a 50
     */
    attributes.forEach(function(attribute) {
      // get all the heroes but the current one
      var rankedHeroes = controller.store.all('superhero');
      rankedHeroes = rankedHeroes.rejectBy('id',controller.get('id'));

      // sort the heroes in order of their absolute difference from the current hero
      rankedHeroes = rankedHeroes.sort(function(a, b) { return Math.abs(controller.get(attribute) - a.get(attribute)) - Math.abs(controller.get(attribute) - b.get(attribute)); });

      // .reverse() reverses the array in place, so stash the results away before building the object
      var similar = rankedHeroes.slice(0,5);

      // weed out everyone who is less than 40 off
      var dissimilar = rankedHeroes.reject(function(hero) { return Math.abs(hero.get(attribute) - controller.get(attribute)) < 41; }).reverse().slice(0,5);
      attributeSimilarities[attribute] = { similar: similar, dissimilar: dissimilar };
    });

    return attributeSimilarities;
  }.property('assertiveness', 'aggressiveness', 'egoDrive', 'empathy', 'egoStrengthResilience', 'riskTaking', 'urgency', 'cautiousness', 'sociability', 'gregariousness', 'accommodation', 'skepticism', 'abstractReasoning', 'ideaOrientation', 'thoroughness', 'flexibility', 'selfStructure', 'externalStructure'),

  /*
   * generate and return a vCard for this hero
   * Mac Address Book/Contacts and Google Contacts can import vCards
   * http://en.wikipedia.org/wiki/VCard
   */
  vCard: function() {
    var vCard = '';
    var firstName = '';
    var lastName = '';

    /* split the full name on whitespace boundaries
     * join all but the last name together as the first name
     */
    var names = this.get('fullName').trim().split(/\s/);
    if(names) {
      lastName = names.pop();
      firstName = names.join(' ');
    } else
      firstName = this.get('fullName');

    vCard += 'BEGIN:VCARD\n';
    vCard += 'VERSION:3.0\n';
    vCard += 'N:' + lastName + ';' + firstName + ';;;\n';
    vCard += 'FN:' + this.get('fullName') + '\n';
    vCard += 'ORG:Precision Nutrition\\, Inc.\n';
    vCard += 'EMAIL;TYPE=PREF,INTERNET:' + this.get('email') + '\n';

    // only set social profile fields if we have them
    if(this.get('twitterUrl'))
     vCard += 'X-SOCIALPROFILE;type=twitter:' + this.get('twitterUrl') + '\n';
    if(this.get('facebookUrl'))
     vCard += 'X-SOCIALPROFILE;type=facebook:' + this.get('facebookUrl') + '\n';
    if(this.get('gpUrl'))
     vCard += 'X-SOCIALPROFILE;type=googleplus:' + this.get('gpUrl') + '\n';

    // set their PN Profile page to be their primary URL
    if(this.get('pnProfileUrl'))
     vCard += 'URL:' + this.get('pnProfileUrl') + '\n';

    // use a default picture unless we have a picUrl and it starts with http
    // TESTME: we may need TYPE=[GIF|JPG|PNG]: before the actual URL
    // FIXME: photo URLs are just not working
    if(this.get('picUrl') && new RegExp(/^http/).test(this.get('picUrl')) )
      vCard += 'PHOTO;VALUE=URL;TYPE=JPG:' + this.get('picUrl') + '\n';
    else
      vCard += 'PHOTO;VALUE=URL;TYPE=PNG:https://fbcdn-profile-a.akamaihd.net/hprofile-ak-ash2/t1.0-1/c7.0.100.100/p100x100/305996_277385985698373_679123386_a.png\n';

    /* this is silly but I didn't manage to find an unadorned PN logo elsewhere and didn't want to spend more time on it
     * also, not sure if any software actually uses the LOGO field
     */
    vCard += 'LOGO;VALUE=URL;TYPE=PNG:https://fbcdn-profile-a.akamaihd.net/hprofile-ak-ash2/t1.0-1/c7.0.100.100/p100x100/305996_277385985698373_679123386_a.png\n';
    vCard += 'CATEGORIES:PN Superheroes\n';
    vCard += 'END:VCARD\n';

    return vCard;
}.property('fullName', 'email', 'picUrl', 'twitterUrl', 'facebookUrl', 'gpUrl', 'pnProfileUrl')
});

Superhero.FIXTURES = [
  {
    id: 1,
    fullName:"Alaina Hardie",
    email: "alaina@precisionnutrition.com",
    picUrl: "/assets/nerd_life.jpg",
    twitterUrl: 'https://twitter.com/trianglegrrl',
    facebookUrl: 'https://facebook.com/alainahardie',
    gplusUrl: 'https://google.com/+AlainaHardie',
    pnProfileUrl: 'http://www.precisionnutrition.com/meet-the-team/alaina-hardie',
    discPicUrl: "/assets/SampleDISC.png",
    whatILove: "Red wine, long walks on the beach, and classless subnetting.",
    whatIHate: "Nazis, snakes, and Nazis.",
    whatINeed: "Compassion, commitment, and $100,000 in unmarked US currency.",
    majorDiscStyle: 'Si',
    superpowers: "Pushups, counting to 10, drop-kicking ill-behaved children.",
    priorities: "Eating, sleeping, making life difficult for The Man.",
    assertiveness:93,
    aggressiveness:2,
    egoDrive:85,
    empathy:73,
    egoStrengthResilience:10,
    riskTaking:78,
    urgency:81,
    cautiousness:3,
    sociability:46,
    gregariousness:12,
    accommodation:67,
    skepticism:14,
    abstractReasoning:95,
    ideaOrientation:97,
    thoroughness:3,
    flexibility:84,
    selfStructure:18,
    externalStructure:2
  },
  {
    id: 2,
    fullName:"Ralph Wiggum",
    email: "ralph@precisionnutrition.com",
    picUrl: "/assets/sloth.jpg",
    twitterUrl: 'https://twitter.com/trianglegrrl',
    facebookUrl: 'https://facebook.com/alainahardie',
    gplusUrl: 'https://google.com/+AlainaHardie',
    pnProfileUrl: 'http://www.precisionnutrition.com/meet-the-team/alaina-hardie',
    discPicUrl: "/assets/SampleDISC.png",
    whatILove: "Red wine, long walks on the beach, and classless subnetting.",
    whatIHate: "Nazis, snakes, and Nazis.",
    whatINeed: "Compassion, commitment, and $100,000 in unmarked US currency.",
    majorDiscStyle: 'SC',
    superpowers: "Pushups, counting to 10, drop-kicking ill-behaved children.",
    priorities: "Eating, sleeping, making life difficult for The Man.",
    assertiveness:93,
    aggressiveness:2,
    egoDrive:9,
    empathy:68,
    egoStrengthResilience:34,
    riskTaking:95,
    urgency:42,
    cautiousness:62,
    sociability:4,
    gregariousness:27,
    accommodation:28,
    skepticism:85,
    abstractReasoning:99,
    ideaOrientation:99,
    thoroughness:91,
    flexibility:44,
    selfStructure:47,
    externalStructure:4
  },
  {
    id: 3,
    fullName:"Kaywinnet Lee Frye",
    email: "kaylee@precisionnutrition.com",
    picUrl: "/assets/sloth.jpg",
    twitterUrl: 'https://twitter.com/trianglegrrl',
    facebookUrl: 'https://facebook.com/alainahardie',
    gplusUrl: 'https://google.com/+AlainaHardie',
    pnProfileUrl: 'http://www.precisionnutrition.com/meet-the-team/alaina-hardie',
    discPicUrl: "/assets/SampleDISC.png",
    whatILove: "Red wine, long walks on the beach, and classless subnetting.",
    whatIHate: "Nazis, snakes, and Nazis.",
    whatINeed: "Compassion, commitment, and $100,000 in unmarked US currency.",
    majorDiscStyle: 'Si',
    superpowers: "Pushups, counting to 10, drop-kicking ill-behaved children.",
    priorities: "Eating, sleeping, making life difficult for The Man.",
    assertiveness:93,
    aggressiveness:2,
    egoDrive:9,
    empathy:68,
    egoStrengthResilience:34,
    riskTaking:95,
    urgency:42,
    cautiousness:62,
    sociability:95,
    gregariousness:27,
    accommodation:28,
    skepticism:85,
    abstractReasoning:99,
    ideaOrientation:99,
    thoroughness:91,
    flexibility:44,
    selfStructure:47,
    externalStructure:4
  },
  {
    id: 4,
    fullName:"Hipster Douchebag",
    email: "yolo@precisionnutrition.com",
    picUrl: "/assets/sloth.jpg",
    twitterUrl: 'https://twitter.com/trianglegrrl',
    facebookUrl: 'https://facebook.com/alainahardie',
    gplusUrl: 'https://google.com/+AlainaHardie',
    pnProfileUrl: 'http://www.precisionnutrition.com/meet-the-team/alaina-hardie',
    discPicUrl: "/assets/SampleDISC.png",
    whatILove: "Red wine, long walks on the beach, and classless subnetting.",
    whatIHate: "Nazis, snakes, and Nazis.",
    whatINeed: "Compassion, commitment, and $100,000 in unmarked US currency.",
    majorDiscStyle: 'SC',
    superpowers: "Pushups, counting to 10, drop-kicking ill-behaved children.",
    priorities: "Eating, sleeping, making life difficult for The Man.",
    assertiveness:93,
    aggressiveness:2,
    egoDrive:9,
    empathy:68,
    egoStrengthResilience:34,
    riskTaking:95,
    urgency:42,
    cautiousness:62,
    sociability:4,
    gregariousness:27,
    accommodation:28,
    skepticism:85,
    abstractReasoning:99,
    ideaOrientation:99,
    thoroughness:91,
    flexibility:44,
    selfStructure:47,
    externalStructure:4
  },
  {
    id: 29,
    fullName:"Krista Scott-Dixon",
    email: "krista@precisionnutrition.com",
    picUrl: "/assets/sloth.jpg",
    twitterUrl: 'https://twitter.com/trianglegrrl',
    facebookUrl: 'https://facebook.com/alainahardie',
    gplusUrl: 'https://google.com/+AlainaHardie',
    pnProfileUrl: 'http://www.precisionnutrition.com/meet-the-team/alaina-hardie',
    discPicUrl: "/assets/SampleDISC.png",
    whatILove: "Red wine, long walks on the beach, and classless subnetting.",
    whatIHate: "Nazis, snakes, and Nazis.",
    whatINeed: "Compassion, commitment, and $100,000 in unmarked US currency.",
    majorDiscStyle: 'i',
    superpowers: "Pushups, counting to 10, drop-kicking ill-behaved children.",
    priorities: "Eating, sleeping, making life difficult for The Man.",
    assertiveness:93,
    aggressiveness:2,
    egoDrive:9,
    empathy:68,
    egoStrengthResilience:34,
    riskTaking:95,
    urgency:42,
    cautiousness:62,
    sociability:4,
    gregariousness:27,
    accommodation:28,
    skepticism:85,
    abstractReasoning:99,
    ideaOrientation:99,
    thoroughness:91,
    flexibility:44,
    selfStructure:47,
    externalStructure:4
  },
   {
      "abstractReasoning" : 37,
      "accommodation" : 60,
      "aggressiveness" : 53,
      "assertiveness" : 93,
      "cautiousness" : 30,
      "discPicUrl" : "/assets/SampleDISC.png",
      "egoDrive" : 40,
      "egoStrengthResilience" : 15,
      "email" : "todd.waylon@precisionnutrition.com",
      "empathy" : 96,
      "externalStructure" : 13,
      "facebookUrl" : "http://facebook.com/toddwaylon",
      "flexibility" : 61,
      "fullName" : "Todd Waylon",
      "gplusUrl" : "http://plus.google.com/+ToddWaylon",
      "gregariousness" : 99,
      "id" : 40,
      "ideaOrientation" : 57,
      "majorDiscStyle" : "Di",
      "picUrl" : "/assets/sloth.jpg",
      "pnProfileUrl" : "http://www.precisionnutrition.com/meet-the-team/todd-waylon",
      "priorities" : "Eating, sleeping, making life difficult for The Man.",
      "riskTaking" : 59,
      "selfStructure" : 24,
      "skepticism" : 97,
      "sociability" : 54,
      "superpowers" : "Pushups, counting to 10, drop-kicking ill-behaved children.",
      "thoroughness" : 92,
      "twitterUrl" : "http://twitter.com/toddwaylon",
      "urgency" : 40,
      "whatIHate" : "Nazis, snakes, and Nazis.",
      "whatILove" : "Red wine, long walks on the beach, and classless subnetting.",
      "whatINeed" : "Compassion, commitment, and $100,000 in unmarked US currency."
   },
   {
      "abstractReasoning" : 4,
      "accommodation" : 89,
      "aggressiveness" : 74,
      "assertiveness" : 93,
      "cautiousness" : 12,
      "discPicUrl" : "/assets/SampleDISC.png",
      "egoDrive" : 82,
      "egoStrengthResilience" : 53,
      "email" : "abraham.burns@precisionnutrition.com",
      "empathy" : 15,
      "externalStructure" : 26,
      "facebookUrl" : "http://facebook.com/abrahamburns",
      "flexibility" : 57,
      "fullName" : "Abraham Burns",
      "gplusUrl" : "http://plus.google.com/+AbrahamBurns",
      "gregariousness" : 76,
      "id" : 41,
      "ideaOrientation" : 93,
      "majorDiscStyle" : "i",
      "picUrl" : "/assets/sloth.jpg",
      "pnProfileUrl" : "http://www.precisionnutrition.com/meet-the-team/abraham-burns",
      "priorities" : "Eating, sleeping, making life difficult for The Man.",
      "riskTaking" : 30,
      "selfStructure" : 74,
      "skepticism" : 39,
      "sociability" : 54,
      "superpowers" : "Pushups, counting to 10, drop-kicking ill-behaved children.",
      "thoroughness" : 94,
      "twitterUrl" : "http://twitter.com/abrahamburns",
      "urgency" : 55,
      "whatIHate" : "Nazis, snakes, and Nazis.",
      "whatILove" : "Red wine, long walks on the beach, and classless subnetting.",
      "whatINeed" : "Compassion, commitment, and $100,000 in unmarked US currency."
   },
   {
      "abstractReasoning" : 2,
      "accommodation" : 18,
      "aggressiveness" : 74,
      "assertiveness" : 93,
      "cautiousness" : 1,
      "discPicUrl" : "/assets/SampleDISC.png",
      "egoDrive" : 20,
      "egoStrengthResilience" : 91,
      "email" : "selma.waylon@precisionnutrition.com",
      "empathy" : 62,
      "externalStructure" : 51,
      "facebookUrl" : "http://facebook.com/selmawaylon",
      "flexibility" : 43,
      "fullName" : "Selma Waylon",
      "gplusUrl" : "http://plus.google.com/+SelmaWaylon",
      "gregariousness" : 78,
      "id" : 42,
      "ideaOrientation" : 27,
      "majorDiscStyle" : "i",
      "picUrl" : "/assets/sloth.jpg",
      "pnProfileUrl" : "http://www.precisionnutrition.com/meet-the-team/selma-waylon",
      "priorities" : "Eating, sleeping, making life difficult for The Man.",
      "riskTaking" : 42,
      "selfStructure" : 89,
      "skepticism" : 20,
      "sociability" : 54,
      "superpowers" : "Pushups, counting to 10, drop-kicking ill-behaved children.",
      "thoroughness" : 11,
      "twitterUrl" : "http://twitter.com/selmawaylon",
      "urgency" : 5,
      "whatIHate" : "Nazis, snakes, and Nazis.",
      "whatILove" : "Red wine, long walks on the beach, and classless subnetting.",
      "whatINeed" : "Compassion, commitment, and $100,000 in unmarked US currency."
   },
   {
      "abstractReasoning" : 33,
      "accommodation" : 5,
      "aggressiveness" : 71,
      "assertiveness" : 93,
      "cautiousness" : 39,
      "discPicUrl" : "/assets/SampleDISC.png",
      "egoDrive" : 9,
      "egoStrengthResilience" : 63,
      "email" : "todd.muntz@precisionnutrition.com",
      "empathy" : 88,
      "externalStructure" : 80,
      "facebookUrl" : "http://facebook.com/toddmuntz",
      "flexibility" : 17,
      "fullName" : "Todd Muntz",
      "gplusUrl" : "http://plus.google.com/+ToddMuntz",
      "gregariousness" : 69,
      "id" : 43,
      "ideaOrientation" : 14,
      "majorDiscStyle" : "D",
      "picUrl" : "/assets/sloth.jpg",
      "pnProfileUrl" : "http://www.precisionnutrition.com/meet-the-team/todd-muntz",
      "priorities" : "Eating, sleeping, making life difficult for The Man.",
      "riskTaking" : 42,
      "selfStructure" : 64,
      "skepticism" : 81,
      "sociability" : 54,
      "superpowers" : "Pushups, counting to 10, drop-kicking ill-behaved children.",
      "thoroughness" : 14,
      "twitterUrl" : "http://twitter.com/toddmuntz",
      "urgency" : 75,
      "whatIHate" : "Nazis, snakes, and Nazis.",
      "whatILove" : "Red wine, long walks on the beach, and classless subnetting.",
      "whatINeed" : "Compassion, commitment, and $100,000 in unmarked US currency."
   },
   {
      "abstractReasoning" : 18,
      "accommodation" : 30,
      "aggressiveness" : 35,
      "assertiveness" : 93,
      "cautiousness" : 70,
      "discPicUrl" : "/assets/SampleDISC.png",
      "egoDrive" : 72,
      "egoStrengthResilience" : 88,
      "email" : "patty.hibbert@precisionnutrition.com",
      "empathy" : 91,
      "externalStructure" : 65,
      "facebookUrl" : "http://facebook.com/pattyhibbert",
      "flexibility" : 47,
      "fullName" : "Patty Hibbert",
      "gplusUrl" : "http://plus.google.com/+PattyHibbert",
      "gregariousness" : 46,
      "id" : 44,
      "ideaOrientation" : 3,
      "majorDiscStyle" : "iS",
      "picUrl" : "/assets/sloth.jpg",
      "pnProfileUrl" : "http://www.precisionnutrition.com/meet-the-team/patty-hibbert",
      "priorities" : "Eating, sleeping, making life difficult for The Man.",
      "riskTaking" : 7,
      "selfStructure" : 49,
      "skepticism" : 26,
      "sociability" : 54,
      "superpowers" : "Pushups, counting to 10, drop-kicking ill-behaved children.",
      "thoroughness" : 5,
      "twitterUrl" : "http://twitter.com/pattyhibbert",
      "urgency" : 22,
      "whatIHate" : "Nazis, snakes, and Nazis.",
      "whatILove" : "Red wine, long walks on the beach, and classless subnetting.",
      "whatINeed" : "Compassion, commitment, and $100,000 in unmarked US currency."
   },
   {
      "abstractReasoning" : 37,
      "accommodation" : 18,
      "aggressiveness" : 89,
      "assertiveness" : 93,
      "cautiousness" : 99,
      "discPicUrl" : "/assets/SampleDISC.png",
      "egoDrive" : 27,
      "egoStrengthResilience" : 99,
      "email" : "maude.burns@precisionnutrition.com",
      "empathy" : 31,
      "externalStructure" : 51,
      "facebookUrl" : "http://facebook.com/maudeburns",
      "flexibility" : 45,
      "fullName" : "Maude Burns",
      "gplusUrl" : "http://plus.google.com/+MaudeBurns",
      "gregariousness" : 68,
      "id" : 45,
      "ideaOrientation" : 49,
      "majorDiscStyle" : "CD",
      "picUrl" : "/assets/sloth.jpg",
      "pnProfileUrl" : "http://www.precisionnutrition.com/meet-the-team/maude-burns",
      "priorities" : "Eating, sleeping, making life difficult for The Man.",
      "riskTaking" : 77,
      "selfStructure" : 74,
      "skepticism" : 42,
      "sociability" : 54,
      "superpowers" : "Pushups, counting to 10, drop-kicking ill-behaved children.",
      "thoroughness" : 69,
      "twitterUrl" : "http://twitter.com/maudeburns",
      "urgency" : 24,
      "whatIHate" : "Nazis, snakes, and Nazis.",
      "whatILove" : "Red wine, long walks on the beach, and classless subnetting.",
      "whatINeed" : "Compassion, commitment, and $100,000 in unmarked US currency."
   },
   {
      "abstractReasoning" : 3,
      "accommodation" : 61,
      "aggressiveness" : 56,
      "assertiveness" : 93,
      "cautiousness" : 6,
      "discPicUrl" : "/assets/SampleDISC.png",
      "egoDrive" : 12,
      "egoStrengthResilience" : 81,
      "email" : "waylon.burns@precisionnutrition.com",
      "empathy" : 30,
      "externalStructure" : 99,
      "facebookUrl" : "http://facebook.com/waylonburns",
      "flexibility" : 90,
      "fullName" : "Waylon Burns",
      "gplusUrl" : "http://plus.google.com/+WaylonBurns",
      "gregariousness" : 65,
      "id" : 46,
      "ideaOrientation" : 71,
      "majorDiscStyle" : "Si",
      "picUrl" : "/assets/sloth.jpg",
      "pnProfileUrl" : "http://www.precisionnutrition.com/meet-the-team/waylon-burns",
      "priorities" : "Eating, sleeping, making life difficult for The Man.",
      "riskTaking" : 43,
      "selfStructure" : 36,
      "skepticism" : 62,
      "sociability" : 54,
      "superpowers" : "Pushups, counting to 10, drop-kicking ill-behaved children.",
      "thoroughness" : 57,
      "twitterUrl" : "http://twitter.com/waylonburns",
      "urgency" : 47,
      "whatIHate" : "Nazis, snakes, and Nazis.",
      "whatILove" : "Red wine, long walks on the beach, and classless subnetting.",
      "whatINeed" : "Compassion, commitment, and $100,000 in unmarked US currency."
   },
   {
      "abstractReasoning" : 41,
      "accommodation" : 26,
      "aggressiveness" : 91,
      "assertiveness" : 93,
      "cautiousness" : 57,
      "discPicUrl" : "/assets/SampleDISC.png",
      "egoDrive" : 26,
      "egoStrengthResilience" : 20,
      "email" : "rod.brockman@precisionnutrition.com",
      "empathy" : 71,
      "externalStructure" : 94,
      "facebookUrl" : "http://facebook.com/rodbrockman",
      "flexibility" : 8,
      "fullName" : "Rod Brockman",
      "gplusUrl" : "http://plus.google.com/+RodBrockman",
      "gregariousness" : 31,
      "id" : 47,
      "ideaOrientation" : 57,
      "majorDiscStyle" : "iD",
      "picUrl" : "/assets/sloth.jpg",
      "pnProfileUrl" : "http://www.precisionnutrition.com/meet-the-team/rod-brockman",
      "priorities" : "Eating, sleeping, making life difficult for The Man.",
      "riskTaking" : 95,
      "selfStructure" : 4,
      "skepticism" : 20,
      "sociability" : 54,
      "superpowers" : "Pushups, counting to 10, drop-kicking ill-behaved children.",
      "thoroughness" : 65,
      "twitterUrl" : "http://twitter.com/rodbrockman",
      "urgency" : 65,
      "whatIHate" : "Nazis, snakes, and Nazis.",
      "whatILove" : "Red wine, long walks on the beach, and classless subnetting.",
      "whatINeed" : "Compassion, commitment, and $100,000 in unmarked US currency."
   },
   {
      "abstractReasoning" : 94,
      "accommodation" : 24,
      "aggressiveness" : 43,
      "assertiveness" : 93,
      "cautiousness" : 26,
      "discPicUrl" : "/assets/SampleDISC.png",
      "egoDrive" : 28,
      "egoStrengthResilience" : 11,
      "email" : "waylon.muntz@precisionnutrition.com",
      "empathy" : 61,
      "externalStructure" : 2,
      "facebookUrl" : "http://facebook.com/waylonmuntz",
      "flexibility" : 6,
      "fullName" : "Waylon Muntz",
      "gplusUrl" : "http://plus.google.com/+WaylonMuntz",
      "gregariousness" : 35,
      "id" : 48,
      "ideaOrientation" : 31,
      "majorDiscStyle" : "i",
      "picUrl" : "/assets/sloth.jpg",
      "pnProfileUrl" : "http://www.precisionnutrition.com/meet-the-team/waylon-muntz",
      "priorities" : "Eating, sleeping, making life difficult for The Man.",
      "riskTaking" : 29,
      "selfStructure" : 31,
      "skepticism" : 79,
      "sociability" : 54,
      "superpowers" : "Pushups, counting to 10, drop-kicking ill-behaved children.",
      "thoroughness" : 43,
      "twitterUrl" : "http://twitter.com/waylonmuntz",
      "urgency" : 21,
      "whatIHate" : "Nazis, snakes, and Nazis.",
      "whatILove" : "Red wine, long walks on the beach, and classless subnetting.",
      "whatINeed" : "Compassion, commitment, and $100,000 in unmarked US currency."
   },
   {
      "abstractReasoning" : 82,
      "accommodation" : 73,
      "aggressiveness" : 93,
      "assertiveness" : 93,
      "cautiousness" : 40,
      "discPicUrl" : "/assets/SampleDISC.png",
      "egoDrive" : 98,
      "egoStrengthResilience" : 16,
      "email" : "homer.simpson@precisionnutrition.com",
      "empathy" : 73,
      "externalStructure" : 57,
      "facebookUrl" : "http://facebook.com/homersimpson",
      "flexibility" : 34,
      "fullName" : "Homer Simpson",
      "gplusUrl" : "http://plus.google.com/+HomerSimpson",
      "gregariousness" : 28,
      "id" : 49,
      "ideaOrientation" : 1,
      "majorDiscStyle" : "",
      "picUrl" : "/assets/sloth.jpg",
      "pnProfileUrl" : "http://www.precisionnutrition.com/meet-the-team/homer-simpson",
      "priorities" : "Eating, sleeping, making life difficult for The Man.",
      "riskTaking" : 76,
      "selfStructure" : 99,
      "skepticism" : 15,
      "sociability" : 54,
      "superpowers" : "Pushups, counting to 10, drop-kicking ill-behaved children.",
      "thoroughness" : 22,
      "twitterUrl" : "http://twitter.com/homersimpson",
      "urgency" : 93,
      "whatIHate" : "Nazis, snakes, and Nazis.",
      "whatILove" : "Red wine, long walks on the beach, and classless subnetting.",
      "whatINeed" : "Compassion, commitment, and $100,000 in unmarked US currency."
   },
   {
      "abstractReasoning" : 53,
      "accommodation" : 17,
      "aggressiveness" : 55,
      "assertiveness" : 93,
      "cautiousness" : 27,
      "discPicUrl" : "/assets/SampleDISC.png",
      "egoDrive" : 51,
      "egoStrengthResilience" : 19,
      "email" : "nelson.muntz@precisionnutrition.com",
      "empathy" : 44,
      "externalStructure" : 10,
      "facebookUrl" : "http://facebook.com/nelsonmuntz",
      "flexibility" : 22,
      "fullName" : "Nelson Muntz",
      "gplusUrl" : "http://plus.google.com/+NelsonMuntz",
      "gregariousness" : 50,
      "id" : 50,
      "ideaOrientation" : 75,
      "majorDiscStyle" : "i",
      "picUrl" : "/assets/sloth.jpg",
      "pnProfileUrl" : "http://www.precisionnutrition.com/meet-the-team/nelson-muntz",
      "priorities" : "Eating, sleeping, making life difficult for The Man.",
      "riskTaking" : 84,
      "selfStructure" : 86,
      "skepticism" : 29,
      "sociability" : 54,
      "superpowers" : "Pushups, counting to 10, drop-kicking ill-behaved children.",
      "thoroughness" : 61,
      "twitterUrl" : "http://twitter.com/nelsonmuntz",
      "urgency" : 89,
      "whatIHate" : "Nazis, snakes, and Nazis.",
      "whatILove" : "Red wine, long walks on the beach, and classless subnetting.",
      "whatINeed" : "Compassion, commitment, and $100,000 in unmarked US currency."
   },
   {
      "abstractReasoning" : 32,
      "accommodation" : 96,
      "aggressiveness" : 74,
      "assertiveness" : 93,
      "cautiousness" : 88,
      "discPicUrl" : "/assets/SampleDISC.png",
      "egoDrive" : 75,
      "egoStrengthResilience" : 42,
      "email" : "ling.flanders@precisionnutrition.com",
      "empathy" : 78,
      "externalStructure" : 72,
      "facebookUrl" : "http://facebook.com/lingflanders",
      "flexibility" : 18,
      "fullName" : "Ling Flanders",
      "gplusUrl" : "http://plus.google.com/+LingFlanders",
      "gregariousness" : 89,
      "id" : 51,
      "ideaOrientation" : 59,
      "majorDiscStyle" : "i",
      "picUrl" : "/assets/sloth.jpg",
      "pnProfileUrl" : "http://www.precisionnutrition.com/meet-the-team/ling-flanders",
      "priorities" : "Eating, sleeping, making life difficult for The Man.",
      "riskTaking" : 84,
      "selfStructure" : 13,
      "skepticism" : 84,
      "sociability" : 54,
      "superpowers" : "Pushups, counting to 10, drop-kicking ill-behaved children.",
      "thoroughness" : 76,
      "twitterUrl" : "http://twitter.com/lingflanders",
      "urgency" : 24,
      "whatIHate" : "Nazis, snakes, and Nazis.",
      "whatILove" : "Red wine, long walks on the beach, and classless subnetting.",
      "whatINeed" : "Compassion, commitment, and $100,000 in unmarked US currency."
   },
   {
      "abstractReasoning" : 47,
      "accommodation" : 75,
      "aggressiveness" : 38,
      "assertiveness" : 93,
      "cautiousness" : 52,
      "discPicUrl" : "/assets/SampleDISC.png",
      "egoDrive" : 91,
      "egoStrengthResilience" : 55,
      "email" : "montgomery.brockman@precisionnutrition.com",
      "empathy" : 74,
      "externalStructure" : 50,
      "facebookUrl" : "http://facebook.com/montgomerybrockman",
      "flexibility" : 76,
      "fullName" : "Montgomery Brockman",
      "gplusUrl" : "http://plus.google.com/+MontgomeryBrockman",
      "gregariousness" : 26,
      "id" : 52,
      "ideaOrientation" : 84,
      "majorDiscStyle" : "i",
      "picUrl" : "/assets/sloth.jpg",
      "pnProfileUrl" : "http://www.precisionnutrition.com/meet-the-team/montgomery-brockman",
      "priorities" : "Eating, sleeping, making life difficult for The Man.",
      "riskTaking" : 13,
      "selfStructure" : 48,
      "skepticism" : 89,
      "sociability" : 54,
      "superpowers" : "Pushups, counting to 10, drop-kicking ill-behaved children.",
      "thoroughness" : 69,
      "twitterUrl" : "http://twitter.com/montgomerybrockman",
      "urgency" : 59,
      "whatIHate" : "Nazis, snakes, and Nazis.",
      "whatILove" : "Red wine, long walks on the beach, and classless subnetting.",
      "whatINeed" : "Compassion, commitment, and $100,000 in unmarked US currency."
   },
   {
      "abstractReasoning" : 71,
      "accommodation" : 28,
      "aggressiveness" : 8,
      "assertiveness" : 93,
      "cautiousness" : 12,
      "discPicUrl" : "/assets/SampleDISC.png",
      "egoDrive" : 58,
      "egoStrengthResilience" : 62,
      "email" : "ling.brockman@precisionnutrition.com",
      "empathy" : 83,
      "externalStructure" : 83,
      "facebookUrl" : "http://facebook.com/lingbrockman",
      "flexibility" : 83,
      "fullName" : "Ling Brockman",
      "gplusUrl" : "http://plus.google.com/+LingBrockman",
      "gregariousness" : 59,
      "id" : 53,
      "ideaOrientation" : 79,
      "majorDiscStyle" : "i",
      "picUrl" : "/assets/sloth.jpg",
      "pnProfileUrl" : "http://www.precisionnutrition.com/meet-the-team/ling-brockman",
      "priorities" : "Eating, sleeping, making life difficult for The Man.",
      "riskTaking" : 12,
      "selfStructure" : 33,
      "skepticism" : 86,
      "sociability" : 54,
      "superpowers" : "Pushups, counting to 10, drop-kicking ill-behaved children.",
      "thoroughness" : 6,
      "twitterUrl" : "http://twitter.com/lingbrockman",
      "urgency" : 57,
      "whatIHate" : "Nazis, snakes, and Nazis.",
      "whatILove" : "Red wine, long walks on the beach, and classless subnetting.",
      "whatINeed" : "Compassion, commitment, and $100,000 in unmarked US currency."
   },
   {
      "abstractReasoning" : 77,
      "accommodation" : 82,
      "aggressiveness" : 46,
      "assertiveness" : 93,
      "cautiousness" : 21,
      "discPicUrl" : "/assets/SampleDISC.png",
      "egoDrive" : 96,
      "egoStrengthResilience" : 93,
      "email" : "maggie.burns@precisionnutrition.com",
      "empathy" : 39,
      "externalStructure" : 77,
      "facebookUrl" : "http://facebook.com/maggieburns",
      "flexibility" : 94,
      "fullName" : "Maggie Burns",
      "gplusUrl" : "http://plus.google.com/+MaggieBurns",
      "gregariousness" : 60,
      "id" : 54,
      "ideaOrientation" : 31,
      "majorDiscStyle" : "i",
      "picUrl" : "/assets/sloth.jpg",
      "pnProfileUrl" : "http://www.precisionnutrition.com/meet-the-team/maggie-burns",
      "priorities" : "Eating, sleeping, making life difficult for The Man.",
      "riskTaking" : 69,
      "selfStructure" : 93,
      "skepticism" : 1,
      "sociability" : 54,
      "superpowers" : "Pushups, counting to 10, drop-kicking ill-behaved children.",
      "thoroughness" : 38,
      "twitterUrl" : "http://twitter.com/maggieburns",
      "urgency" : 28,
      "whatIHate" : "Nazis, snakes, and Nazis.",
      "whatILove" : "Red wine, long walks on the beach, and classless subnetting.",
      "whatINeed" : "Compassion, commitment, and $100,000 in unmarked US currency."
   },
   {
      "abstractReasoning" : 46,
      "accommodation" : 50,
      "aggressiveness" : 16,
      "assertiveness" : 93,
      "cautiousness" : 95,
      "discPicUrl" : "/assets/SampleDISC.png",
      "egoDrive" : 60,
      "egoStrengthResilience" : 42,
      "email" : "todd.hibbert@precisionnutrition.com",
      "empathy" : 77,
      "externalStructure" : 13,
      "facebookUrl" : "http://facebook.com/toddhibbert",
      "flexibility" : 67,
      "fullName" : "Todd Hibbert",
      "gplusUrl" : "http://plus.google.com/+ToddHibbert",
      "gregariousness" : 30,
      "id" : 55,
      "ideaOrientation" : 60,
      "majorDiscStyle" : "i",
      "picUrl" : "/assets/sloth.jpg",
      "pnProfileUrl" : "http://www.precisionnutrition.com/meet-the-team/todd-hibbert",
      "priorities" : "Eating, sleeping, making life difficult for The Man.",
      "riskTaking" : 89,
      "selfStructure" : 48,
      "skepticism" : 73,
      "sociability" : 54,
      "superpowers" : "Pushups, counting to 10, drop-kicking ill-behaved children.",
      "thoroughness" : 90,
      "twitterUrl" : "http://twitter.com/toddhibbert",
      "urgency" : 35,
      "whatIHate" : "Nazis, snakes, and Nazis.",
      "whatILove" : "Red wine, long walks on the beach, and classless subnetting.",
      "whatINeed" : "Compassion, commitment, and $100,000 in unmarked US currency."
   },
   {
      "abstractReasoning" : 65,
      "accommodation" : 87,
      "aggressiveness" : 31,
      "assertiveness" : 93,
      "cautiousness" : 91,
      "discPicUrl" : "/assets/SampleDISC.png",
      "egoDrive" : 60,
      "egoStrengthResilience" : 67,
      "email" : "rod.bouvier@precisionnutrition.com",
      "empathy" : 35,
      "externalStructure" : 20,
      "facebookUrl" : "http://facebook.com/rodbouvier",
      "flexibility" : 25,
      "fullName" : "Rod Bouvier",
      "gplusUrl" : "http://plus.google.com/+RodBouvier",
      "gregariousness" : 25,
      "id" : 56,
      "ideaOrientation" : 49,
      "majorDiscStyle" : "i",
      "picUrl" : "/assets/sloth.jpg",
      "pnProfileUrl" : "http://www.precisionnutrition.com/meet-the-team/rod-bouvier",
      "priorities" : "Eating, sleeping, making life difficult for The Man.",
      "riskTaking" : 71,
      "selfStructure" : 44,
      "skepticism" : 80,
      "sociability" : 54,
      "superpowers" : "Pushups, counting to 10, drop-kicking ill-behaved children.",
      "thoroughness" : 23,
      "twitterUrl" : "http://twitter.com/rodbouvier",
      "urgency" : 49,
      "whatIHate" : "Nazis, snakes, and Nazis.",
      "whatILove" : "Red wine, long walks on the beach, and classless subnetting.",
      "whatINeed" : "Compassion, commitment, and $100,000 in unmarked US currency."
   },
   {
      "abstractReasoning" : 1,
      "accommodation" : 48,
      "aggressiveness" : 75,
      "assertiveness" : 93,
      "cautiousness" : 27,
      "discPicUrl" : "/assets/SampleDISC.png",
      "egoDrive" : 64,
      "egoStrengthResilience" : 62,
      "email" : "diamond joe.simpson@precisionnutrition.com",
      "empathy" : 21,
      "externalStructure" : 93,
      "facebookUrl" : "http://facebook.com/diamond joesimpson",
      "flexibility" : 94,
      "fullName" : "Diamond Joe Simpson",
      "gplusUrl" : "http://plus.google.com/+Diamond JoeSimpson",
      "gregariousness" : 78,
      "id" : 57,
      "ideaOrientation" : 47,
      "majorDiscStyle" : "i",
      "picUrl" : "/assets/sloth.jpg",
      "pnProfileUrl" : "http://www.precisionnutrition.com/meet-the-team/diamond joe-simpson",
      "priorities" : "Eating, sleeping, making life difficult for The Man.",
      "riskTaking" : 65,
      "selfStructure" : 71,
      "skepticism" : 9,
      "sociability" : 54,
      "superpowers" : "Pushups, counting to 10, drop-kicking ill-behaved children.",
      "thoroughness" : 76,
      "twitterUrl" : "http://twitter.com/diamond joesimpson",
      "urgency" : 47,
      "whatIHate" : "Nazis, snakes, and Nazis.",
      "whatILove" : "Red wine, long walks on the beach, and classless subnetting.",
      "whatINeed" : "Compassion, commitment, and $100,000 in unmarked US currency."
   },
   {
      "abstractReasoning" : 28,
      "accommodation" : 50,
      "aggressiveness" : 47,
      "assertiveness" : 93,
      "cautiousness" : 42,
      "discPicUrl" : "/assets/SampleDISC.png",
      "egoDrive" : 41,
      "egoStrengthResilience" : 81,
      "email" : "ling.burns@precisionnutrition.com",
      "empathy" : 22,
      "externalStructure" : 48,
      "facebookUrl" : "http://facebook.com/lingburns",
      "flexibility" : 30,
      "fullName" : "Ling Burns",
      "gplusUrl" : "http://plus.google.com/+LingBurns",
      "gregariousness" : 41,
      "id" : 58,
      "ideaOrientation" : 65,
      "majorDiscStyle" : "i",
      "picUrl" : "/assets/sloth.jpg",
      "pnProfileUrl" : "http://www.precisionnutrition.com/meet-the-team/ling-burns",
      "priorities" : "Eating, sleeping, making life difficult for The Man.",
      "riskTaking" : 30,
      "selfStructure" : 44,
      "skepticism" : 100,
      "sociability" : 54,
      "superpowers" : "Pushups, counting to 10, drop-kicking ill-behaved children.",
      "thoroughness" : 81,
      "twitterUrl" : "http://twitter.com/lingburns",
      "urgency" : 8,
      "whatIHate" : "Nazis, snakes, and Nazis.",
      "whatILove" : "Red wine, long walks on the beach, and classless subnetting.",
      "whatINeed" : "Compassion, commitment, and $100,000 in unmarked US currency."
   },
   {
      "abstractReasoning" : 90,
      "accommodation" : 95,
      "aggressiveness" : 93,
      "assertiveness" : 93,
      "cautiousness" : 50,
      "discPicUrl" : "/assets/SampleDISC.png",
      "egoDrive" : 88,
      "egoStrengthResilience" : 60,
      "email" : "marge.brockman@precisionnutrition.com",
      "empathy" : 35,
      "externalStructure" : 9,
      "facebookUrl" : "http://facebook.com/margebrockman",
      "flexibility" : 21,
      "fullName" : "Marge Brockman",
      "gplusUrl" : "http://plus.google.com/+MargeBrockman",
      "gregariousness" : 16,
      "id" : 59,
      "ideaOrientation" : 79,
      "majorDiscStyle" : "i",
      "picUrl" : "/assets/sloth.jpg",
      "pnProfileUrl" : "http://www.precisionnutrition.com/meet-the-team/marge-brockman",
      "priorities" : "Eating, sleeping, making life difficult for The Man.",
      "riskTaking" : 65,
      "selfStructure" : 22,
      "skepticism" : 69,
      "sociability" : 54,
      "superpowers" : "Pushups, counting to 10, drop-kicking ill-behaved children.",
      "thoroughness" : 84,
      "twitterUrl" : "http://twitter.com/margebrockman",
      "urgency" : 96,
      "whatIHate" : "Nazis, snakes, and Nazis.",
      "whatILove" : "Red wine, long walks on the beach, and classless subnetting.",
      "whatINeed" : "Compassion, commitment, and $100,000 in unmarked US currency."
   },
   {
      "abstractReasoning" : 45,
      "accommodation" : 30,
      "aggressiveness" : 83,
      "assertiveness" : 93,
      "cautiousness" : 74,
      "discPicUrl" : "/assets/SampleDISC.png",
      "egoDrive" : 60,
      "egoStrengthResilience" : 59,
      "email" : "seymour.muntz@precisionnutrition.com",
      "empathy" : 39,
      "externalStructure" : 19,
      "facebookUrl" : "http://facebook.com/seymourmuntz",
      "flexibility" : 46,
      "fullName" : "Seymour Muntz",
      "gplusUrl" : "http://plus.google.com/+SeymourMuntz",
      "gregariousness" : 11,
      "id" : 60,
      "ideaOrientation" : 99,
      "majorDiscStyle" : "i",
      "picUrl" : "/assets/sloth.jpg",
      "pnProfileUrl" : "http://www.precisionnutrition.com/meet-the-team/seymour-muntz",
      "priorities" : "Eating, sleeping, making life difficult for The Man.",
      "riskTaking" : 21,
      "selfStructure" : 52,
      "skepticism" : 25,
      "sociability" : 54,
      "superpowers" : "Pushups, counting to 10, drop-kicking ill-behaved children.",
      "thoroughness" : 1,
      "twitterUrl" : "http://twitter.com/seymourmuntz",
      "urgency" : 37,
      "whatIHate" : "Nazis, snakes, and Nazis.",
      "whatILove" : "Red wine, long walks on the beach, and classless subnetting.",
      "whatINeed" : "Compassion, commitment, and $100,000 in unmarked US currency."
   },
   {
      "abstractReasoning" : 14,
      "accommodation" : 21,
      "aggressiveness" : 99,
      "assertiveness" : 93,
      "cautiousness" : 62,
      "discPicUrl" : "/assets/SampleDISC.png",
      "egoDrive" : 69,
      "egoStrengthResilience" : 91,
      "email" : "waylon.flanders@precisionnutrition.com",
      "empathy" : 76,
      "externalStructure" : 19,
      "facebookUrl" : "http://facebook.com/waylonflanders",
      "flexibility" : 45,
      "fullName" : "Waylon Flanders",
      "gplusUrl" : "http://plus.google.com/+WaylonFlanders",
      "gregariousness" : 75,
      "id" : 61,
      "ideaOrientation" : 88,
      "majorDiscStyle" : "i",
      "picUrl" : "/assets/sloth.jpg",
      "pnProfileUrl" : "http://www.precisionnutrition.com/meet-the-team/waylon-flanders",
      "priorities" : "Eating, sleeping, making life difficult for The Man.",
      "riskTaking" : 51,
      "selfStructure" : 9,
      "skepticism" : 29,
      "sociability" : 54,
      "superpowers" : "Pushups, counting to 10, drop-kicking ill-behaved children.",
      "thoroughness" : 29,
      "twitterUrl" : "http://twitter.com/waylonflanders",
      "urgency" : 11,
      "whatIHate" : "Nazis, snakes, and Nazis.",
      "whatILove" : "Red wine, long walks on the beach, and classless subnetting.",
      "whatINeed" : "Compassion, commitment, and $100,000 in unmarked US currency."
   },
   {
      "abstractReasoning" : 38,
      "accommodation" : 46,
      "aggressiveness" : 78,
      "assertiveness" : 93,
      "cautiousness" : 5,
      "discPicUrl" : "/assets/SampleDISC.png",
      "egoDrive" : 10,
      "egoStrengthResilience" : 71,
      "email" : "seymour.hibbert@precisionnutrition.com",
      "empathy" : 95,
      "externalStructure" : 40,
      "facebookUrl" : "http://facebook.com/seymourhibbert",
      "flexibility" : 14,
      "fullName" : "Seymour Hibbert",
      "gplusUrl" : "http://plus.google.com/+SeymourHibbert",
      "gregariousness" : 81,
      "id" : 62,
      "ideaOrientation" : 34,
      "majorDiscStyle" : "i",
      "picUrl" : "/assets/sloth.jpg",
      "pnProfileUrl" : "http://www.precisionnutrition.com/meet-the-team/seymour-hibbert",
      "priorities" : "Eating, sleeping, making life difficult for The Man.",
      "riskTaking" : 29,
      "selfStructure" : 13,
      "skepticism" : 40,
      "sociability" : 54,
      "superpowers" : "Pushups, counting to 10, drop-kicking ill-behaved children.",
      "thoroughness" : 7,
      "twitterUrl" : "http://twitter.com/seymourhibbert",
      "urgency" : 18,
      "whatIHate" : "Nazis, snakes, and Nazis.",
      "whatILove" : "Red wine, long walks on the beach, and classless subnetting.",
      "whatINeed" : "Compassion, commitment, and $100,000 in unmarked US currency."
   },
   {
      "abstractReasoning" : 29,
      "accommodation" : 76,
      "aggressiveness" : 23,
      "assertiveness" : 93,
      "cautiousness" : 39,
      "discPicUrl" : "/assets/SampleDISC.png",
      "egoDrive" : 73,
      "egoStrengthResilience" : 76,
      "email" : "maggie.waylon@precisionnutrition.com",
      "empathy" : 16,
      "externalStructure" : 86,
      "facebookUrl" : "http://facebook.com/maggiewaylon",
      "flexibility" : 15,
      "fullName" : "Maggie Waylon",
      "gplusUrl" : "http://plus.google.com/+MaggieWaylon",
      "gregariousness" : 26,
      "id" : 63,
      "ideaOrientation" : 96,
      "majorDiscStyle" : "i",
      "picUrl" : "/assets/sloth.jpg",
      "pnProfileUrl" : "http://www.precisionnutrition.com/meet-the-team/maggie-waylon",
      "priorities" : "Eating, sleeping, making life difficult for The Man.",
      "riskTaking" : 38,
      "selfStructure" : 4,
      "skepticism" : 50,
      "sociability" : 54,
      "superpowers" : "Pushups, counting to 10, drop-kicking ill-behaved children.",
      "thoroughness" : 43,
      "twitterUrl" : "http://twitter.com/maggiewaylon",
      "urgency" : 14,
      "whatIHate" : "Nazis, snakes, and Nazis.",
      "whatILove" : "Red wine, long walks on the beach, and classless subnetting.",
      "whatINeed" : "Compassion, commitment, and $100,000 in unmarked US currency."
   },
   {
      "abstractReasoning" : 24,
      "accommodation" : 3,
      "aggressiveness" : 84,
      "assertiveness" : 93,
      "cautiousness" : 9,
      "discPicUrl" : "/assets/SampleDISC.png",
      "egoDrive" : 89,
      "egoStrengthResilience" : 97,
      "email" : "ling.muntz@precisionnutrition.com",
      "empathy" : 80,
      "externalStructure" : 26,
      "facebookUrl" : "http://facebook.com/lingmuntz",
      "flexibility" : 38,
      "fullName" : "Ling Muntz",
      "gplusUrl" : "http://plus.google.com/+LingMuntz",
      "gregariousness" : 95,
      "id" : 64,
      "ideaOrientation" : 69,
      "majorDiscStyle" : "i",
      "picUrl" : "/assets/sloth.jpg",
      "pnProfileUrl" : "http://www.precisionnutrition.com/meet-the-team/ling-muntz",
      "priorities" : "Eating, sleeping, making life difficult for The Man.",
      "riskTaking" : 87,
      "selfStructure" : 85,
      "skepticism" : 30,
      "sociability" : 54,
      "superpowers" : "Pushups, counting to 10, drop-kicking ill-behaved children.",
      "thoroughness" : 5,
      "twitterUrl" : "http://twitter.com/lingmuntz",
      "urgency" : 88,
      "whatIHate" : "Nazis, snakes, and Nazis.",
      "whatILove" : "Red wine, long walks on the beach, and classless subnetting.",
      "whatINeed" : "Compassion, commitment, and $100,000 in unmarked US currency."
   },
   {
      "abstractReasoning" : 20,
      "accommodation" : 84,
      "aggressiveness" : 100,
      "assertiveness" : 93,
      "cautiousness" : 56,
      "discPicUrl" : "/assets/SampleDISC.png",
      "egoDrive" : 7,
      "egoStrengthResilience" : 86,
      "email" : "marge.muntz@precisionnutrition.com",
      "empathy" : 68,
      "externalStructure" : 28,
      "facebookUrl" : "http://facebook.com/margemuntz",
      "flexibility" : 76,
      "fullName" : "Marge Muntz",
      "gplusUrl" : "http://plus.google.com/+MargeMuntz",
      "gregariousness" : 56,
      "id" : 65,
      "ideaOrientation" : 52,
      "majorDiscStyle" : "i",
      "picUrl" : "/assets/sloth.jpg",
      "pnProfileUrl" : "http://www.precisionnutrition.com/meet-the-team/marge-muntz",
      "priorities" : "Eating, sleeping, making life difficult for The Man.",
      "riskTaking" : 96,
      "selfStructure" : 64,
      "skepticism" : 19,
      "sociability" : 54,
      "superpowers" : "Pushups, counting to 10, drop-kicking ill-behaved children.",
      "thoroughness" : 95,
      "twitterUrl" : "http://twitter.com/margemuntz",
      "urgency" : 17,
      "whatIHate" : "Nazis, snakes, and Nazis.",
      "whatILove" : "Red wine, long walks on the beach, and classless subnetting.",
      "whatINeed" : "Compassion, commitment, and $100,000 in unmarked US currency."
   },
   {
      "abstractReasoning" : 3,
      "accommodation" : 36,
      "aggressiveness" : 15,
      "assertiveness" : 93,
      "cautiousness" : 2,
      "discPicUrl" : "/assets/SampleDISC.png",
      "egoDrive" : 51,
      "egoStrengthResilience" : 37,
      "email" : "patty.muntz@precisionnutrition.com",
      "empathy" : 97,
      "externalStructure" : 52,
      "facebookUrl" : "http://facebook.com/pattymuntz",
      "flexibility" : 83,
      "fullName" : "Patty Muntz",
      "gplusUrl" : "http://plus.google.com/+PattyMuntz",
      "gregariousness" : 24,
      "id" : 66,
      "ideaOrientation" : 86,
      "majorDiscStyle" : "i",
      "picUrl" : "/assets/sloth.jpg",
      "pnProfileUrl" : "http://www.precisionnutrition.com/meet-the-team/patty-muntz",
      "priorities" : "Eating, sleeping, making life difficult for The Man.",
      "riskTaking" : 82,
      "selfStructure" : 81,
      "skepticism" : 58,
      "sociability" : 54,
      "superpowers" : "Pushups, counting to 10, drop-kicking ill-behaved children.",
      "thoroughness" : 54,
      "twitterUrl" : "http://twitter.com/pattymuntz",
      "urgency" : 13,
      "whatIHate" : "Nazis, snakes, and Nazis.",
      "whatILove" : "Red wine, long walks on the beach, and classless subnetting.",
      "whatINeed" : "Compassion, commitment, and $100,000 in unmarked US currency."
   },
   {
      "abstractReasoning" : 100,
      "accommodation" : 11,
      "aggressiveness" : 75,
      "assertiveness" : 93,
      "cautiousness" : 32,
      "discPicUrl" : "/assets/SampleDISC.png",
      "egoDrive" : 89,
      "egoStrengthResilience" : 61,
      "email" : "patty.quimby@precisionnutrition.com",
      "empathy" : 35,
      "externalStructure" : 18,
      "facebookUrl" : "http://facebook.com/pattyquimby",
      "flexibility" : 83,
      "fullName" : "Patty Quimby",
      "gplusUrl" : "http://plus.google.com/+PattyQuimby",
      "gregariousness" : 77,
      "id" : 67,
      "ideaOrientation" : 22,
      "majorDiscStyle" : "Di",
      "picUrl" : "/assets/sloth.jpg",
      "pnProfileUrl" : "http://www.precisionnutrition.com/meet-the-team/patty-quimby",
      "priorities" : "Eating, sleeping, making life difficult for The Man.",
      "riskTaking" : 3,
      "selfStructure" : 21,
      "skepticism" : 72,
      "sociability" : 54,
      "superpowers" : "Pushups, counting to 10, drop-kicking ill-behaved children.",
      "thoroughness" : 3,
      "twitterUrl" : "http://twitter.com/pattyquimby",
      "urgency" : 15,
      "whatIHate" : "Nazis, snakes, and Nazis.",
      "whatILove" : "Red wine, long walks on the beach, and classless subnetting.",
      "whatINeed" : "Compassion, commitment, and $100,000 in unmarked US currency."
   },
   {
      "abstractReasoning" : 87,
      "accommodation" : 35,
      "aggressiveness" : 28,
      "assertiveness" : 93,
      "cautiousness" : 100,
      "discPicUrl" : "/assets/SampleDISC.png",
      "egoDrive" : 46,
      "egoStrengthResilience" : 44,
      "email" : "selma.hibbert@precisionnutrition.com",
      "empathy" : 25,
      "externalStructure" : 97,
      "facebookUrl" : "http://facebook.com/selmahibbert",
      "flexibility" : 52,
      "fullName" : "Selma Hibbert",
      "gplusUrl" : "http://plus.google.com/+SelmaHibbert",
      "gregariousness" : 69,
      "id" : 68,
      "ideaOrientation" : 25,
      "majorDiscStyle" : "Di",
      "picUrl" : "/assets/sloth.jpg",
      "pnProfileUrl" : "http://www.precisionnutrition.com/meet-the-team/selma-hibbert",
      "priorities" : "Eating, sleeping, making life difficult for The Man.",
      "riskTaking" : 25,
      "selfStructure" : 91,
      "skepticism" : 42,
      "sociability" : 54,
      "superpowers" : "Pushups, counting to 10, drop-kicking ill-behaved children.",
      "thoroughness" : 5,
      "twitterUrl" : "http://twitter.com/selmahibbert",
      "urgency" : 72,
      "whatIHate" : "Nazis, snakes, and Nazis.",
      "whatILove" : "Red wine, long walks on the beach, and classless subnetting.",
      "whatINeed" : "Compassion, commitment, and $100,000 in unmarked US currency."
   },
   {
      "abstractReasoning" : 25,
      "accommodation" : 58,
      "aggressiveness" : 100,
      "assertiveness" : 93,
      "cautiousness" : 81,
      "discPicUrl" : "/assets/SampleDISC.png",
      "egoDrive" : 48,
      "egoStrengthResilience" : 62,
      "email" : "ned.bouvier@precisionnutrition.com",
      "empathy" : 14,
      "externalStructure" : 96,
      "facebookUrl" : "http://facebook.com/nedbouvier",
      "flexibility" : 85,
      "fullName" : "Ned Bouvier",
      "gplusUrl" : "http://plus.google.com/+NedBouvier",
      "gregariousness" : 92,
      "id" : 69,
      "ideaOrientation" : 95,
      "majorDiscStyle" : "Di",
      "picUrl" : "/assets/sloth.jpg",
      "pnProfileUrl" : "http://www.precisionnutrition.com/meet-the-team/ned-bouvier",
      "priorities" : "Eating, sleeping, making life difficult for The Man.",
      "riskTaking" : 31,
      "selfStructure" : 85,
      "skepticism" : 36,
      "sociability" : 54,
      "superpowers" : "Pushups, counting to 10, drop-kicking ill-behaved children.",
      "thoroughness" : 50,
      "twitterUrl" : "http://twitter.com/nedbouvier",
      "urgency" : 25,
      "whatIHate" : "Nazis, snakes, and Nazis.",
      "whatILove" : "Red wine, long walks on the beach, and classless subnetting.",
      "whatINeed" : "Compassion, commitment, and $100,000 in unmarked US currency."
   }
];

export default Superhero;
